### ISSUE TITLE
Master not building

### ISSUE THREAD

**Issue by krl** [dusk-network/phoenix-abi#34]
As of may 18, this code does not build anymore from master.

Among other errors is this api breakage:

```
71 |             GadgetStrategy::poseidon_gadget(composer, pi, &mut perm);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --------  --  --------- supplied 3 arguments
   |             |
   |             expected 2 arguments
```

**Comment by CPerezz** [comment]
I can help you with this. Probably it's a dependency problem. Should be solved quickly.

**Comment by CPerezz** [comment]
Remove PI and it should work.
